# Generated by Selenium IDE
import pdb 
from selenium.webdriver.common.keys import Keys
from glob import glob
from selenium import webdriver
import time
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait 




class TestDefaultSuite():

  def __init__(self):
    self.driver = webdriver.Firefox(executable_path=r'C:\Users\Sandro Bispo\Desktop\Py_tons_prog\importar_web\geckodriver.exe')
    
    self.driver.get("https://www.absolar.org.br/nossos-associados/")
    self.driver.set_window_size(1344, 763)
    for k in range(1,5):
          for x in self.driver.find_elements_by_class_name("tooltip1"):

              self.salvar_registro()
  
                

  def salvar_registro(self):
        with open(r'C:\Users\Sandro Bispo\Desktop\Documento.txt','a') as f:
              try:
                    f.write(self.driver.find_element_by_class_name("tooltip1").text+'\n')
              except:
                    f.write(self.driver.find_element_by_xpath("/html/body/main/div[3]/div/div/div[1]/div/p[2]/a").text+'\n')
       



TestDefaultSuite()

