# Generated by Selenium IDE
import pdb 
from selenium.webdriver.common.keys import Keys
from glob import glob
from selenium import webdriver
import time
from selenium.webdriver.common.by import By



class TestDefaultSuite():

  def __init__(self):
    self.driver = webdriver.Firefox(executable_path=r'C:\Users\Sandro Bispo\Desktop\Py_tons_prog\importar_web\geckodriver.exe')
    self.driver.get("https://cib.dpr.gov.br/Home/PesquisaCompleta")
    self.driver.set_window_size(1344, 763)
    self.driver.find_element_by_id("btn-pesquisa").click()
    for k in range(1,7467):
        for x in self.driver.find_elements_by_class_name("item-lista"):
            x.click()
            time.sleep(1)
            with open(r'C:\Users\Sandro Bispo\Desktop\Documento.txt','a') as f:
                f.write(self.driver.find_elements_by_class_name("valor")[1].text+'\n')
            self.driver.find_element_by_tag_name('body').send_keys(Keys.ESCAPE)
            time.sleep(1)
        self.driver.find_element_by_css_selector("a[title='Próxima página']").click()
TestDefaultSuite()

#sandro.bispo@mtrends.com.br
#Sbi#0104

# for k,e in enumerate()): 
#     print(k,e.text)
#     self.driver.find_elements_by_class_name("valor")