# Generated by Selenium IDE
import pdb 
from selenium.webdriver.common.keys import Keys
from glob import glob
from selenium import webdriver
import time
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait 




class TestDefaultSuite():

  def __init__(self):
    self.driver = webdriver.Firefox(executable_path=r'C:\Users\Sandro Bispo\Desktop\Py_tons_prog\importar_web\geckodriver.exe')
    
    self.driver.get("https://www.portalsolar.com.br/fornecedores/empresas-de-energia-solar/lista")
    self.driver.set_window_size(1344, 763)
    for k in range(1,53):
          for x in self.driver.find_elements_by_class_name("logo"):
                self.fechar_modal()
                self.volta_aba_principal()
                time.sleep(3)
                x.click()
                time.sleep(1)
                self.ultima_aba()
                time.sleep(3)
                self.fechar_modal()
                self.salvar_registro()
                self.volta_aba_principal()
          self.driver.find_element_by_class_name("next").click()
                
                
  def ultima_aba(self):
      self.driver.switch_to_window(self.driver.window_handles[-1])

  
  def volta_aba_principal(self):
        self.driver.switch_to_window(self.driver.window_handles[0])
  
  def salvar_registro(self):
        with open(r'C:\Users\Sandro Bispo\Desktop\Documento.txt','a') as f:
          f.write(self.driver.find_element_by_xpath("/html/body/div[1]/div[2]/div[2]/div/div[1]/div[4]").text+'\n')
          time.sleep(5)
          self.driver.close()

  def fechar_modal(self):
        time.sleep(3)
        try:
            self.driver.find_element_by_xpath("/html/body/div[13]/div/div/button").click()
        except:
              pass

TestDefaultSuite()

